version: '3'
services:
  apollo-gateway:
    container_name: apollo-gateway
    build: ./gateway
    environment:
      - APOLLO_SCHEMA_CONFIG_EMBEDDED=true
    volumes:
      - ./supergraph.graphql:/etc/config/supergraph.graphql
    ports:
      - "4000:4000"
  clubs:
    container_name: clubs
    build: ./subgraphs/clubs
  posts:
    container_name: posts
    build: ./subgraphs/posts
  thumbnail:
    container_name: thumbnail
    build: ./subgraphs/thumbnail
